import type { NextPage } from "next";
import Head from "next/head";

import StyledSection from "../components/styles/Section.styled";
import Socials from "../components/reusable/Socials";

const Home: NextPage = () => {
  const Section = StyledSection;
  return (
    <>
      <Head>
        <title>Adrian Cristallo's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section>
        <Socials github linkedin gmail vertAlign="top" />
      </Section>
    </>
  );
};

export default Home;
