import type { NextPage } from "next";
import Head from "next/head";

import { StyledMain as Main } from "../components/styledComponents";
import Section from "../components/reusable/Section";
import Projects from "../components/main/projects/Projects";
import About from "../components/main/about/About";
import Contact from "../components/main/contact/Contact";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Adrian Cristallo's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Section id="about" title="About">
          <About />
        </Section>
        <Section id="projects" title="Projects">
          <Projects />
        </Section>
        <Section id="contact" title="Contact">
          <Contact />
        </Section>
      </Main>
    </>
  );
};

export default Home;
