const projectData = [
  {
    id: "1",
    title: "CheckList",
    desc: "This is a single page Vanilla JavaScript project on GitHub",
    repoLink: "https://github.com/haheha24/CheckList",
    deployLink: "https://haheha24.github.io/CheckList/",
    tags: ["JavaScript", "HTML", "CSS"],
    completed: false,
    stars: 2,
  },
  {
    id: "2",
    title: "Lookup",
    desc: "This is a single page MERN stack project on GitHub",
    repoLink: "https://github.com/haheha24/lookup-repo",
    deployLink: "https://lookup-project.herokuapp.com/",
    tags: [
      "JavaScript",
      "React",
      "Node.JS",
      "Express.JS",
      "Mongoose.JS",
      "MongoDB Atlas",
      "HTML",
      "CSS",
    ],
    completed: true,
    stars: 2,
  },
  {
    id: "3",
    title: "FCC: Technical Documentation Page",
    desc: "This is a single page JavaScript project done on my codepen.io",
    repoLink: "https://codepen.io/haheha24/pen/VwPdxeB",
    deployLink: "",
    tags: ["HTML", "CSS", "JavaScript"],
    completed: true,
    stars: 1,
  },
  {
    id: "4",
    title: "Product Landing Page",
    desc: "This is a single page Product Landing Page project done on my codepen.io",
    repoLink: "https://codepen.io/haheha24/pen/poRVGZQ",
    deployLink: "",
    tags: ["HTML", "CSS"],
    completed: true,
    stars: 1,
  },
  {
    id: "5",
    title: "FCC: Survey Form",
    desc: "This is a single page Survey Form project done on my codepen.io",
    repoLink: "https://codepen.io/haheha24/pen/LYxmYVL",
    deployLink: "",
    tags: ["HTML", "CSS"],
    completed: true,
    stars: 1,
  },
  {
    id: "6",
    title: "FCC: Tribute Page",
    desc: "This is a single page FCC: Tribute Page project done on my codepen.io",
    repoLink: "https://codepen.io/haheha24/pen/XWpMxqL",
    deployLink: "",
    tags: ["HTML", "CSS"],
    completed: true,
    stars: 1,
  },
];

export default projectData;
